name: Lint Python code

on:
  push:
    branches:
      - main
    paths-ignore:
      - "assets/**"
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "assets/**"
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Ruff
        run: pip install ruff

      - name: Run linter
        run: ruff check .
